//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace Alfresco.ActionWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ActionServiceSoapBinding", Namespace="http://www.alfresco.org/ws/service/action/1.0")]
    public partial class ActionService : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback getConditionDefinitionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getActionDefinitionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getActionItemDefinitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRuleTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRuleTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getActionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveActionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeActionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback executeActionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRulesOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveRulesOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeRulesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ActionService() {
            this.Url = global::Alfresco.Properties.Settings.Default.Alfresco_ActionWebService_ActionService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getConditionDefinitionsCompletedEventHandler getConditionDefinitionsCompleted;
        
        /// <remarks/>
        public event getActionDefinitionsCompletedEventHandler getActionDefinitionsCompleted;
        
        /// <remarks/>
        public event getActionItemDefinitionCompletedEventHandler getActionItemDefinitionCompleted;
        
        /// <remarks/>
        public event getRuleTypesCompletedEventHandler getRuleTypesCompleted;
        
        /// <remarks/>
        public event getRuleTypeCompletedEventHandler getRuleTypeCompleted;
        
        /// <remarks/>
        public event getActionsCompletedEventHandler getActionsCompleted;
        
        /// <remarks/>
        public event saveActionsCompletedEventHandler saveActionsCompleted;
        
        /// <remarks/>
        public event removeActionsCompletedEventHandler removeActionsCompleted;
        
        /// <remarks/>
        public event executeActionsCompletedEventHandler executeActionsCompleted;
        
        /// <remarks/>
        public event getRulesCompletedEventHandler getRulesCompleted;
        
        /// <remarks/>
        public event saveRulesCompletedEventHandler saveRulesCompleted;
        
        /// <remarks/>
        public event removeRulesCompletedEventHandler removeRulesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/getConditionDefinitions", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("actionItemDefinition")]
        public ActionItemDefinition[] getConditionDefinitions() {
            object[] results = this.Invoke("getConditionDefinitions", new object[0]);
            return ((ActionItemDefinition[])(results[0]));
        }
        
        /// <remarks/>
        public void getConditionDefinitionsAsync() {
            this.getConditionDefinitionsAsync(null);
        }
        
        /// <remarks/>
        public void getConditionDefinitionsAsync(object userState) {
            if ((this.getConditionDefinitionsOperationCompleted == null)) {
                this.getConditionDefinitionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetConditionDefinitionsOperationCompleted);
            }
            this.InvokeAsync("getConditionDefinitions", new object[0], this.getConditionDefinitionsOperationCompleted, userState);
        }
        
        private void OngetConditionDefinitionsOperationCompleted(object arg) {
            if ((this.getConditionDefinitionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getConditionDefinitionsCompleted(this, new getConditionDefinitionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/getActionDefinitions", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("actionItemDefinition")]
        public ActionItemDefinition[] getActionDefinitions() {
            object[] results = this.Invoke("getActionDefinitions", new object[0]);
            return ((ActionItemDefinition[])(results[0]));
        }
        
        /// <remarks/>
        public void getActionDefinitionsAsync() {
            this.getActionDefinitionsAsync(null);
        }
        
        /// <remarks/>
        public void getActionDefinitionsAsync(object userState) {
            if ((this.getActionDefinitionsOperationCompleted == null)) {
                this.getActionDefinitionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetActionDefinitionsOperationCompleted);
            }
            this.InvokeAsync("getActionDefinitions", new object[0], this.getActionDefinitionsOperationCompleted, userState);
        }
        
        private void OngetActionDefinitionsOperationCompleted(object arg) {
            if ((this.getActionDefinitionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getActionDefinitionsCompleted(this, new getActionDefinitionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/getActionItemDefinition", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("actionItemDefinition")]
        public ActionItemDefinition getActionItemDefinition(string name, ActionItemDefinitionType definitionType) {
            object[] results = this.Invoke("getActionItemDefinition", new object[] {
                        name,
                        definitionType});
            return ((ActionItemDefinition)(results[0]));
        }
        
        /// <remarks/>
        public void getActionItemDefinitionAsync(string name, ActionItemDefinitionType definitionType) {
            this.getActionItemDefinitionAsync(name, definitionType, null);
        }
        
        /// <remarks/>
        public void getActionItemDefinitionAsync(string name, ActionItemDefinitionType definitionType, object userState) {
            if ((this.getActionItemDefinitionOperationCompleted == null)) {
                this.getActionItemDefinitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetActionItemDefinitionOperationCompleted);
            }
            this.InvokeAsync("getActionItemDefinition", new object[] {
                        name,
                        definitionType}, this.getActionItemDefinitionOperationCompleted, userState);
        }
        
        private void OngetActionItemDefinitionOperationCompleted(object arg) {
            if ((this.getActionItemDefinitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getActionItemDefinitionCompleted(this, new getActionItemDefinitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/getRuleTypes", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ruleType")]
        public RuleType[] getRuleTypes() {
            object[] results = this.Invoke("getRuleTypes", new object[0]);
            return ((RuleType[])(results[0]));
        }
        
        /// <remarks/>
        public void getRuleTypesAsync() {
            this.getRuleTypesAsync(null);
        }
        
        /// <remarks/>
        public void getRuleTypesAsync(object userState) {
            if ((this.getRuleTypesOperationCompleted == null)) {
                this.getRuleTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRuleTypesOperationCompleted);
            }
            this.InvokeAsync("getRuleTypes", new object[0], this.getRuleTypesOperationCompleted, userState);
        }
        
        private void OngetRuleTypesOperationCompleted(object arg) {
            if ((this.getRuleTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRuleTypesCompleted(this, new getRuleTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/getRuleType", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ruleType")]
        public RuleType getRuleType(string name) {
            object[] results = this.Invoke("getRuleType", new object[] {
                        name});
            return ((RuleType)(results[0]));
        }
        
        /// <remarks/>
        public void getRuleTypeAsync(string name) {
            this.getRuleTypeAsync(name, null);
        }
        
        /// <remarks/>
        public void getRuleTypeAsync(string name, object userState) {
            if ((this.getRuleTypeOperationCompleted == null)) {
                this.getRuleTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRuleTypeOperationCompleted);
            }
            this.InvokeAsync("getRuleType", new object[] {
                        name}, this.getRuleTypeOperationCompleted, userState);
        }
        
        private void OngetRuleTypeOperationCompleted(object arg) {
            if ((this.getRuleTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRuleTypeCompleted(this, new getRuleTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/getActions", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("action")]
        public Action[] getActions(Reference reference, ActionFilter filter) {
            object[] results = this.Invoke("getActions", new object[] {
                        reference,
                        filter});
            return ((Action[])(results[0]));
        }
        
        /// <remarks/>
        public void getActionsAsync(Reference reference, ActionFilter filter) {
            this.getActionsAsync(reference, filter, null);
        }
        
        /// <remarks/>
        public void getActionsAsync(Reference reference, ActionFilter filter, object userState) {
            if ((this.getActionsOperationCompleted == null)) {
                this.getActionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetActionsOperationCompleted);
            }
            this.InvokeAsync("getActions", new object[] {
                        reference,
                        filter}, this.getActionsOperationCompleted, userState);
        }
        
        private void OngetActionsOperationCompleted(object arg) {
            if ((this.getActionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getActionsCompleted(this, new getActionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/saveActions", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("action")]
        public Action[] saveActions(Reference reference, [System.Xml.Serialization.XmlElementAttribute("actions")] Action[] actions) {
            object[] results = this.Invoke("saveActions", new object[] {
                        reference,
                        actions});
            return ((Action[])(results[0]));
        }
        
        /// <remarks/>
        public void saveActionsAsync(Reference reference, Action[] actions) {
            this.saveActionsAsync(reference, actions, null);
        }
        
        /// <remarks/>
        public void saveActionsAsync(Reference reference, Action[] actions, object userState) {
            if ((this.saveActionsOperationCompleted == null)) {
                this.saveActionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveActionsOperationCompleted);
            }
            this.InvokeAsync("saveActions", new object[] {
                        reference,
                        actions}, this.saveActionsOperationCompleted, userState);
        }
        
        private void OnsaveActionsOperationCompleted(object arg) {
            if ((this.saveActionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveActionsCompleted(this, new saveActionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/removeActions", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void removeActions(Reference reference, [System.Xml.Serialization.XmlElementAttribute("actions", IsNullable=true)] Action[] actions) {
            this.Invoke("removeActions", new object[] {
                        reference,
                        actions});
        }
        
        /// <remarks/>
        public void removeActionsAsync(Reference reference, Action[] actions) {
            this.removeActionsAsync(reference, actions, null);
        }
        
        /// <remarks/>
        public void removeActionsAsync(Reference reference, Action[] actions, object userState) {
            if ((this.removeActionsOperationCompleted == null)) {
                this.removeActionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveActionsOperationCompleted);
            }
            this.InvokeAsync("removeActions", new object[] {
                        reference,
                        actions}, this.removeActionsOperationCompleted, userState);
        }
        
        private void OnremoveActionsOperationCompleted(object arg) {
            if ((this.removeActionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeActionsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/executeActions", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("actionExecutionResult")]
        public ActionExecutionResult[] executeActions(Predicate predicate, [System.Xml.Serialization.XmlElementAttribute("actions")] Action[] actions) {
            object[] results = this.Invoke("executeActions", new object[] {
                        predicate,
                        actions});
            return ((ActionExecutionResult[])(results[0]));
        }
        
        /// <remarks/>
        public void executeActionsAsync(Predicate predicate, Action[] actions) {
            this.executeActionsAsync(predicate, actions, null);
        }
        
        /// <remarks/>
        public void executeActionsAsync(Predicate predicate, Action[] actions, object userState) {
            if ((this.executeActionsOperationCompleted == null)) {
                this.executeActionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecuteActionsOperationCompleted);
            }
            this.InvokeAsync("executeActions", new object[] {
                        predicate,
                        actions}, this.executeActionsOperationCompleted, userState);
        }
        
        private void OnexecuteActionsOperationCompleted(object arg) {
            if ((this.executeActionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.executeActionsCompleted(this, new executeActionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/getRules", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("rule")]
        public Rule[] getRules(Reference reference, RuleFilter ruleFilter) {
            object[] results = this.Invoke("getRules", new object[] {
                        reference,
                        ruleFilter});
            return ((Rule[])(results[0]));
        }
        
        /// <remarks/>
        public void getRulesAsync(Reference reference, RuleFilter ruleFilter) {
            this.getRulesAsync(reference, ruleFilter, null);
        }
        
        /// <remarks/>
        public void getRulesAsync(Reference reference, RuleFilter ruleFilter, object userState) {
            if ((this.getRulesOperationCompleted == null)) {
                this.getRulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRulesOperationCompleted);
            }
            this.InvokeAsync("getRules", new object[] {
                        reference,
                        ruleFilter}, this.getRulesOperationCompleted, userState);
        }
        
        private void OngetRulesOperationCompleted(object arg) {
            if ((this.getRulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRulesCompleted(this, new getRulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/saveRules", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("rule")]
        public Rule[] saveRules(Reference reference, [System.Xml.Serialization.XmlElementAttribute("rules")] Rule[] rules) {
            object[] results = this.Invoke("saveRules", new object[] {
                        reference,
                        rules});
            return ((Rule[])(results[0]));
        }
        
        /// <remarks/>
        public void saveRulesAsync(Reference reference, Rule[] rules) {
            this.saveRulesAsync(reference, rules, null);
        }
        
        /// <remarks/>
        public void saveRulesAsync(Reference reference, Rule[] rules, object userState) {
            if ((this.saveRulesOperationCompleted == null)) {
                this.saveRulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveRulesOperationCompleted);
            }
            this.InvokeAsync("saveRules", new object[] {
                        reference,
                        rules}, this.saveRulesOperationCompleted, userState);
        }
        
        private void OnsaveRulesOperationCompleted(object arg) {
            if ((this.saveRulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveRulesCompleted(this, new saveRulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/action/1.0/removeRules", RequestNamespace="http://www.alfresco.org/ws/service/action/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/action/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void removeRules(Reference reference, [System.Xml.Serialization.XmlElementAttribute("rules", IsNullable=true)] Rule[] rules) {
            this.Invoke("removeRules", new object[] {
                        reference,
                        rules});
        }
        
        /// <remarks/>
        public void removeRulesAsync(Reference reference, Rule[] rules) {
            this.removeRulesAsync(reference, rules, null);
        }
        
        /// <remarks/>
        public void removeRulesAsync(Reference reference, Rule[] rules, object userState) {
            if ((this.removeRulesOperationCompleted == null)) {
                this.removeRulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveRulesOperationCompleted);
            }
            this.InvokeAsync("removeRules", new object[] {
                        reference,
                        rules}, this.removeRulesOperationCompleted, userState);
        }
        
        private void OnremoveRulesOperationCompleted(object arg) {
            if ((this.removeRulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeRulesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/action/1.0")]
    public partial class ActionItemDefinition {
        
        private string nameField;
        
        private ActionItemDefinitionType typeField;
        
        private string titleField;
        
        private string descriptionField;
        
        private bool adHocPropertiesAllowedField;
        
        private ParameterDefinition[] parameterDefinitionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public ActionItemDefinitionType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool adHocPropertiesAllowed {
            get {
                return this.adHocPropertiesAllowedField;
            }
            set {
                this.adHocPropertiesAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameterDefinition", IsNullable=true)]
        public ParameterDefinition[] parameterDefinition {
            get {
                return this.parameterDefinitionField;
            }
            set {
                this.parameterDefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/action/1.0")]
    public enum ActionItemDefinitionType {
        
        /// <remarks/>
        action,
        
        /// <remarks/>
        condition,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/action/1.0")]
    public partial class ParameterDefinition {
        
        private string nameField;
        
        private string typeField;
        
        private bool isMandatoryField;
        
        private string displayLabelField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public bool isMandatory {
            get {
                return this.isMandatoryField;
            }
            set {
                this.isMandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string displayLabel {
            get {
                return this.displayLabelField;
            }
            set {
                this.displayLabelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/action/1.0")]
    public partial class Rule {
        
        private string idField;
        
        private string ruleTypeField;
        
        private string titleField;
        
        private string descriptionField;
        
        private bool executeAsynchronouslyField;
        
        private Condition[] conditionsField;
        
        private Action[] actionsField;
        
        private string runAsUserNameField;
        
        private Reference referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ruleType {
            get {
                return this.ruleTypeField;
            }
            set {
                this.ruleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool executeAsynchronously {
            get {
                return this.executeAsynchronouslyField;
            }
            set {
                this.executeAsynchronouslyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("conditions", IsNullable=true)]
        public Condition[] conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actions")]
        public Action[] actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string runAsUserName {
            get {
                return this.runAsUserNameField;
            }
            set {
                this.runAsUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Reference reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/action/1.0")]
    public partial class Condition {
        
        private string idField;
        
        private string conditionNameField;
        
        private bool invertConditionField;
        
        private NamedValue[] parametersField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string conditionName {
            get {
                return this.conditionNameField;
            }
            set {
                this.conditionNameField = value;
            }
        }
        
        /// <remarks/>
        public bool invertCondition {
            get {
                return this.invertConditionField;
            }
            set {
                this.invertConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameters", IsNullable=true)]
        public NamedValue[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class NamedValue {
        
        private string nameField;
        
        private System.Nullable<bool> isMultiValueField;
        
        private string valueField;
        
        private string[] valuesField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isMultiValue {
            get {
                return this.isMultiValueField;
            }
            set {
                this.isMultiValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("values", IsNullable=true)]
        public string[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/action/1.0")]
    public partial class Action {
        
        private string idField;
        
        private string actionNameField;
        
        private string titleField;
        
        private string descriptionField;
        
        private bool executeAsynchronouslyField;
        
        private NamedValue[] parametersField;
        
        private Condition[] conditionsField;
        
        private Action compensatingActionField;
        
        private Action[] actionsField;
        
        private Reference referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string actionName {
            get {
                return this.actionNameField;
            }
            set {
                this.actionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool executeAsynchronously {
            get {
                return this.executeAsynchronouslyField;
            }
            set {
                this.executeAsynchronouslyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameters", IsNullable=true)]
        public NamedValue[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("conditions", IsNullable=true)]
        public Condition[] conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Action compensatingAction {
            get {
                return this.compensatingActionField;
            }
            set {
                this.compensatingActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actions", IsNullable=true)]
        public Action[] actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Reference reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParentReference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Reference {
        
        private Store storeField;
        
        private string uuidField;
        
        private string pathField;
        
        public Reference() {
            this.pathField = "/";
        }
        
        /// <remarks/>
        public Store store {
            get {
                return this.storeField;
            }
            set {
                this.storeField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("/")]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Store {
        
        private StoreEnum schemeField;
        
        private string addressField;
        
        /// <remarks/>
        public StoreEnum scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public enum StoreEnum {
        
        /// <remarks/>
        workspace,
        
        /// <remarks/>
        versionStore,
        
        /// <remarks/>
        user,
        
        /// <remarks/>
        search,
        
        /// <remarks/>
        http,
        
        /// <remarks/>
        system,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ParentReference : Reference {
        
        private string associationTypeField;
        
        private string childNameField;
        
        /// <remarks/>
        public string associationType {
            get {
                return this.associationTypeField;
            }
            set {
                this.associationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string childName {
            get {
                return this.childNameField;
            }
            set {
                this.childNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/action/1.0")]
    public partial class RuleFilter {
        
        private string[] idsField;
        
        private string[] ruleTypeNamesField;
        
        private bool includeInheritedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ids", IsNullable=true)]
        public string[] ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleTypeNames", IsNullable=true)]
        public string[] ruleTypeNames {
            get {
                return this.ruleTypeNamesField;
            }
            set {
                this.ruleTypeNamesField = value;
            }
        }
        
        /// <remarks/>
        public bool includeInherited {
            get {
                return this.includeInheritedField;
            }
            set {
                this.includeInheritedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/action/1.0")]
    public partial class ActionExecutionResult {
        
        private Reference referenceField;
        
        private Action[] actionsField;
        
        /// <remarks/>
        public Reference reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actions", IsNullable=true)]
        public Action[] actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Query {
        
        private QueryLanguageEnum languageField;
        
        private string statementField;
        
        /// <remarks/>
        public QueryLanguageEnum language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string statement {
            get {
                return this.statementField;
            }
            set {
                this.statementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public enum QueryLanguageEnum {
        
        /// <remarks/>
        lucene,
        
        /// <remarks/>
        xpath,
        
        /// <remarks/>
        cql,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Predicate {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nodes", typeof(Reference), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("query", typeof(Query), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("store", typeof(Store), IsNullable=true)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/action/1.0")]
    public partial class ActionFilter {
        
        private string[] idsField;
        
        private string[] typesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ids", IsNullable=true)]
        public string[] ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("types", IsNullable=true)]
        public string[] types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/action/1.0")]
    public partial class RuleType {
        
        private string nameField;
        
        private string displayLabelField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string displayLabel {
            get {
                return this.displayLabelField;
            }
            set {
                this.displayLabelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getConditionDefinitionsCompletedEventHandler(object sender, getConditionDefinitionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getConditionDefinitionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getConditionDefinitionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionItemDefinition[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionItemDefinition[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getActionDefinitionsCompletedEventHandler(object sender, getActionDefinitionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getActionDefinitionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getActionDefinitionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionItemDefinition[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionItemDefinition[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getActionItemDefinitionCompletedEventHandler(object sender, getActionItemDefinitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getActionItemDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getActionItemDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionItemDefinition Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionItemDefinition)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getRuleTypesCompletedEventHandler(object sender, getRuleTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRuleTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRuleTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RuleType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RuleType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getRuleTypeCompletedEventHandler(object sender, getRuleTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRuleTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRuleTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RuleType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RuleType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getActionsCompletedEventHandler(object sender, getActionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getActionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getActionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Action[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Action[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void saveActionsCompletedEventHandler(object sender, saveActionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveActionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveActionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Action[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Action[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void removeActionsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void executeActionsCompletedEventHandler(object sender, executeActionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class executeActionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal executeActionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActionExecutionResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActionExecutionResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getRulesCompletedEventHandler(object sender, getRulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rule[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rule[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void saveRulesCompletedEventHandler(object sender, saveRulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveRulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveRulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rule[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rule[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void removeRulesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591