//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace Alfresco.AdministrationWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdministrationServiceSoapBinding", Namespace="http://www.alfresco.org/ws/service/administration/1.0")]
    public partial class AdministrationService : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback queryUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchMoreUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback createUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback changePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteUsersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdministrationService() {
            this.Url = global::Alfresco.Properties.Settings.Default.Alfresco_AdministrationWebService_AdministrationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event queryUsersCompletedEventHandler queryUsersCompleted;
        
        /// <remarks/>
        public event fetchMoreUsersCompletedEventHandler fetchMoreUsersCompleted;
        
        /// <remarks/>
        public event getUserCompletedEventHandler getUserCompleted;
        
        /// <remarks/>
        public event createUsersCompletedEventHandler createUsersCompleted;
        
        /// <remarks/>
        public event updateUsersCompletedEventHandler updateUsersCompleted;
        
        /// <remarks/>
        public event changePasswordCompletedEventHandler changePasswordCompleted;
        
        /// <remarks/>
        public event deleteUsersCompletedEventHandler deleteUsersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/administration/1.0/queryUsers", RequestNamespace="http://www.alfresco.org/ws/service/administration/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/administration/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public UserQueryResults queryUsers(UserFilter filter) {
            object[] results = this.Invoke("queryUsers", new object[] {
                        filter});
            return ((UserQueryResults)(results[0]));
        }
        
        /// <remarks/>
        public void queryUsersAsync(UserFilter filter) {
            this.queryUsersAsync(filter, null);
        }
        
        /// <remarks/>
        public void queryUsersAsync(UserFilter filter, object userState) {
            if ((this.queryUsersOperationCompleted == null)) {
                this.queryUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryUsersOperationCompleted);
            }
            this.InvokeAsync("queryUsers", new object[] {
                        filter}, this.queryUsersOperationCompleted, userState);
        }
        
        private void OnqueryUsersOperationCompleted(object arg) {
            if ((this.queryUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryUsersCompleted(this, new queryUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/administration/1.0/fetchMoreUsers", RequestNamespace="http://www.alfresco.org/ws/service/administration/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/administration/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public UserQueryResults fetchMoreUsers(string querySession) {
            object[] results = this.Invoke("fetchMoreUsers", new object[] {
                        querySession});
            return ((UserQueryResults)(results[0]));
        }
        
        /// <remarks/>
        public void fetchMoreUsersAsync(string querySession) {
            this.fetchMoreUsersAsync(querySession, null);
        }
        
        /// <remarks/>
        public void fetchMoreUsersAsync(string querySession, object userState) {
            if ((this.fetchMoreUsersOperationCompleted == null)) {
                this.fetchMoreUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchMoreUsersOperationCompleted);
            }
            this.InvokeAsync("fetchMoreUsers", new object[] {
                        querySession}, this.fetchMoreUsersOperationCompleted, userState);
        }
        
        private void OnfetchMoreUsersOperationCompleted(object arg) {
            if ((this.fetchMoreUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchMoreUsersCompleted(this, new fetchMoreUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/administration/1.0/getUser", RequestNamespace="http://www.alfresco.org/ws/service/administration/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/administration/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public UserDetails getUser(string userName) {
            object[] results = this.Invoke("getUser", new object[] {
                        userName});
            return ((UserDetails)(results[0]));
        }
        
        /// <remarks/>
        public void getUserAsync(string userName) {
            this.getUserAsync(userName, null);
        }
        
        /// <remarks/>
        public void getUserAsync(string userName, object userState) {
            if ((this.getUserOperationCompleted == null)) {
                this.getUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserOperationCompleted);
            }
            this.InvokeAsync("getUser", new object[] {
                        userName}, this.getUserOperationCompleted, userState);
        }
        
        private void OngetUserOperationCompleted(object arg) {
            if ((this.getUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserCompleted(this, new getUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/administration/1.0/createUsers", RequestNamespace="http://www.alfresco.org/ws/service/administration/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/administration/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public UserDetails[] createUsers([System.Xml.Serialization.XmlElementAttribute("newUsers")] NewUserDetails[] newUsers) {
            object[] results = this.Invoke("createUsers", new object[] {
                        newUsers});
            return ((UserDetails[])(results[0]));
        }
        
        /// <remarks/>
        public void createUsersAsync(NewUserDetails[] newUsers) {
            this.createUsersAsync(newUsers, null);
        }
        
        /// <remarks/>
        public void createUsersAsync(NewUserDetails[] newUsers, object userState) {
            if ((this.createUsersOperationCompleted == null)) {
                this.createUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateUsersOperationCompleted);
            }
            this.InvokeAsync("createUsers", new object[] {
                        newUsers}, this.createUsersOperationCompleted, userState);
        }
        
        private void OncreateUsersOperationCompleted(object arg) {
            if ((this.createUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createUsersCompleted(this, new createUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/administration/1.0/updateUsers", RequestNamespace="http://www.alfresco.org/ws/service/administration/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/administration/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public UserDetails[] updateUsers([System.Xml.Serialization.XmlElementAttribute("users")] UserDetails[] users) {
            object[] results = this.Invoke("updateUsers", new object[] {
                        users});
            return ((UserDetails[])(results[0]));
        }
        
        /// <remarks/>
        public void updateUsersAsync(UserDetails[] users) {
            this.updateUsersAsync(users, null);
        }
        
        /// <remarks/>
        public void updateUsersAsync(UserDetails[] users, object userState) {
            if ((this.updateUsersOperationCompleted == null)) {
                this.updateUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateUsersOperationCompleted);
            }
            this.InvokeAsync("updateUsers", new object[] {
                        users}, this.updateUsersOperationCompleted, userState);
        }
        
        private void OnupdateUsersOperationCompleted(object arg) {
            if ((this.updateUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateUsersCompleted(this, new updateUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/administration/1.0/changePassword", RequestNamespace="http://www.alfresco.org/ws/service/administration/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/administration/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void changePassword(string userName, string oldPassword, string newPassword) {
            this.Invoke("changePassword", new object[] {
                        userName,
                        oldPassword,
                        newPassword});
        }
        
        /// <remarks/>
        public void changePasswordAsync(string userName, string oldPassword, string newPassword) {
            this.changePasswordAsync(userName, oldPassword, newPassword, null);
        }
        
        /// <remarks/>
        public void changePasswordAsync(string userName, string oldPassword, string newPassword, object userState) {
            if ((this.changePasswordOperationCompleted == null)) {
                this.changePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangePasswordOperationCompleted);
            }
            this.InvokeAsync("changePassword", new object[] {
                        userName,
                        oldPassword,
                        newPassword}, this.changePasswordOperationCompleted, userState);
        }
        
        private void OnchangePasswordOperationCompleted(object arg) {
            if ((this.changePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changePasswordCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/administration/1.0/deleteUsers", RequestNamespace="http://www.alfresco.org/ws/service/administration/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/administration/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteUsers([System.Xml.Serialization.XmlElementAttribute("userNames")] string[] userNames) {
            this.Invoke("deleteUsers", new object[] {
                        userNames});
        }
        
        /// <remarks/>
        public void deleteUsersAsync(string[] userNames) {
            this.deleteUsersAsync(userNames, null);
        }
        
        /// <remarks/>
        public void deleteUsersAsync(string[] userNames, object userState) {
            if ((this.deleteUsersOperationCompleted == null)) {
                this.deleteUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteUsersOperationCompleted);
            }
            this.InvokeAsync("deleteUsers", new object[] {
                        userNames}, this.deleteUsersOperationCompleted, userState);
        }
        
        private void OndeleteUsersOperationCompleted(object arg) {
            if ((this.deleteUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteUsersCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/administration/1.0")]
    public partial class UserFilter {
        
        private string userNameField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/administration/1.0")]
    public partial class NewUserDetails {
        
        private string userNameField;
        
        private string passwordField;
        
        private NamedValue[] propertiesField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties")]
        public NamedValue[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class NamedValue {
        
        private string nameField;
        
        private System.Nullable<bool> isMultiValueField;
        
        private string valueField;
        
        private string[] valuesField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isMultiValue {
            get {
                return this.isMultiValueField;
            }
            set {
                this.isMultiValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("values", IsNullable=true)]
        public string[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/administration/1.0")]
    public partial class UserDetails {
        
        private string userNameField;
        
        private NamedValue[] propertiesField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties")]
        public NamedValue[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/administration/1.0")]
    public partial class UserQueryResults {
        
        private string querySessionField;
        
        private UserDetails[] userDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string querySession {
            get {
                return this.querySessionField;
            }
            set {
                this.querySessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userDetails")]
        public UserDetails[] userDetails {
            get {
                return this.userDetailsField;
            }
            set {
                this.userDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void queryUsersCompletedEventHandler(object sender, queryUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserQueryResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserQueryResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void fetchMoreUsersCompletedEventHandler(object sender, fetchMoreUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchMoreUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchMoreUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserQueryResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserQueryResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getUserCompletedEventHandler(object sender, getUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void createUsersCompletedEventHandler(object sender, createUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserDetails[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserDetails[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void updateUsersCompletedEventHandler(object sender, updateUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserDetails[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserDetails[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void changePasswordCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void deleteUsersCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591