//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alfresco.RepositoryWebService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RepositoryServiceSoapBinding", Namespace="http://www.alfresco.org/ws/service/repository/1.0")]
    public partial class RepositoryService : Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        public QueryConfiguration QueryConfigurationValue;
        
        /// <remarks/>
        public RepositoryService()
        {
            this.Url = "http://localhost:8080/alfresco/api/RepositoryService";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/createStore", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("createStoreReturn")]
        public Store createStore(string scheme, string address)
        {
            object[] results = this.Invoke("createStore", new object[] {
                        scheme,
                        address});
            return ((Store)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateStore(string scheme, string address, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("createStore", new object[] {
                        scheme,
                        address}, callback, asyncState);
        }
        
        /// <remarks/>
        public Store EndcreateStore(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Store)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/getStores", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getStoresReturn")]
        public Store[] getStores()
        {
            object[] results = this.Invoke("getStores", new object[0]);
            return ((Store[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetStores(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getStores", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Store[] EndgetStores(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Store[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("QueryConfigurationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/query", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryReturn")]
        public QueryResult query(Store store, [System.Xml.Serialization.XmlElementAttribute("query")] Query query1, bool includeMetaData)
        {
            object[] results = this.Invoke("query", new object[] {
                        store,
                        query1,
                        includeMetaData});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginquery(Store store, Query query1, bool includeMetaData, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("query", new object[] {
                        store,
                        query1,
                        includeMetaData}, callback, asyncState);
        }
        
        /// <remarks/>
        public QueryResult Endquery(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("QueryConfigurationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/queryChildren", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryReturn")]
        public QueryResult queryChildren(Reference node)
        {
            object[] results = this.Invoke("queryChildren", new object[] {
                        node});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryChildren(Reference node, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("queryChildren", new object[] {
                        node}, callback, asyncState);
        }
        
        /// <remarks/>
        public QueryResult EndqueryChildren(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("QueryConfigurationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/queryParents", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryReturn")]
        public QueryResult queryParents(Reference node)
        {
            object[] results = this.Invoke("queryParents", new object[] {
                        node});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryParents(Reference node, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("queryParents", new object[] {
                        node}, callback, asyncState);
        }
        
        /// <remarks/>
        public QueryResult EndqueryParents(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("QueryConfigurationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/queryAssociated", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryReturn")]
        public QueryResult queryAssociated(Reference node, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Association association)
        {
            object[] results = this.Invoke("queryAssociated", new object[] {
                        node,
                        association});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryAssociated(Reference node, Association association, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("queryAssociated", new object[] {
                        node,
                        association}, callback, asyncState);
        }
        
        /// <remarks/>
        public QueryResult EndqueryAssociated(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/fetchMore", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryReturn")]
        public QueryResult fetchMore(string querySession)
        {
            object[] results = this.Invoke("fetchMore", new object[] {
                        querySession});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfetchMore(string querySession, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchMore", new object[] {
                        querySession}, callback, asyncState);
        }
        
        /// <remarks/>
        public QueryResult EndfetchMore(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/update", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateReturn")]
        public UpdateResult[] update(CML statements)
        {
            object[] results = this.Invoke("update", new object[] {
                        statements});
            return ((UpdateResult[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate(CML statements, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("update", new object[] {
                        statements}, callback, asyncState);
        }
        
        /// <remarks/>
        public UpdateResult[] Endupdate(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((UpdateResult[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/describe", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("describeReturn")]
        public NodeDefinition[] describe(Predicate items)
        {
            object[] results = this.Invoke("describe", new object[] {
                        items});
            return ((NodeDefinition[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindescribe(Predicate items, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("describe", new object[] {
                        items}, callback, asyncState);
        }
        
        /// <remarks/>
        public NodeDefinition[] Enddescribe(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((NodeDefinition[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/repository/1.0/get", RequestNamespace="http://www.alfresco.org/ws/service/repository/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/repository/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getReturn")]
        public Node[] get(Predicate @where)
        {
            object[] results = this.Invoke("get", new object[] {
                        @where});
            return ((Node[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget(Predicate @where, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get", new object[] {
                        @where}, callback, asyncState);
        }
        
        /// <remarks/>
        public Node[] Endget(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Node[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public enum StoreEnum {
        
        /// <remarks/>
        workspace,
        
        /// <remarks/>
        versionStore,
        
        /// <remarks/>
        user,
        
        /// <remarks/>
        search,
        
        /// <remarks/>
        http,
        
        /// <remarks/>
        system,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/headers/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.alfresco.org/ws/service/repository/1.0", IsNullable=false)]
    public partial class QueryConfiguration : System.Web.Services.Protocols.SoapHeader
    {
        
        /// <remarks/>
        public int fetchSize;
        
        public QueryConfiguration()
        {
            this.fetchSize = 500;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Node
    {
        
        /// <remarks/>
        public Reference reference;
        
        /// <remarks/>
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aspects")]
        public string[] aspects;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties")]
        public NamedValue[] properties;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParentReference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Reference
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Store store;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [System.ComponentModel.DefaultValueAttribute("/")]
        public string path;
        
        public Reference()
        {
            this.path = "/";
        }
    }
    
/// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Store {
        
        private StoreEnum schemeField;
        
        private string addressField;
        
        /// <remarks/>
        public StoreEnum scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ParentReference : Reference
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string associationType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string childName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class NamedValue
    {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isMultiValue;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("values", IsNullable=true)]
        public string[] values;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class NodeDefinition
    {
        
        /// <remarks/>
        public ClassDefinition type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aspects")]
        public ClassDefinition[] aspects;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ClassDefinition
    {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string description;
        
        /// <remarks/>
        public string superClass;
        
        /// <remarks/>
        public bool isAspect;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties", IsNullable=true)]
        public PropertyDefinition[] properties;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("associations", IsNullable=true)]
        public AssociationDefinition[] associations;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class PropertyDefinition : ValueDefinition
    {
        
        /// <remarks/>
        public bool mandatory;
        
        /// <remarks/>
        public bool readOnly;
        
        /// <remarks/>
        public string defaultValue;
        
        public PropertyDefinition()
        {
            this.mandatory = false;
            this.readOnly = false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyDefinition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ValueDefinition
    {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string description;
        
        /// <remarks/>
        public string dataType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class AssociationDefinition
    {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string description;
        
        /// <remarks/>
        public bool isChild;
        
        /// <remarks/>
        public RoleDefinition sourceRole;
        
        /// <remarks/>
        public RoleDefinition targetRole;
        
        /// <remarks/>
        public string targetClass;
        
        public AssociationDefinition()
        {
            this.isChild = true;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class RoleDefinition
    {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(Cardinality.Item)]
        public Cardinality cardinality;
        
        public RoleDefinition()
        {
            this.cardinality = Cardinality.Item;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public enum Cardinality
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0..1")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("*")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1..*")]
        Item11,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/repository/1.0")]
    public partial class UpdateResult
    {
        
        /// <remarks/>
        public string statement;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultSet updateCount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sourceId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Reference source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Reference destination;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ResultSet
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rows")]
        public ResultSetRow[] rows;
        
        /// <remarks/>
        public long totalRowCount;
        
        /// <remarks/>
        public ResultSetMetaData metaData;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ResultSetRow
    {
        
        /// <remarks/>
        public long rowIndex;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("columns")]
        public NamedValue[] columns;
        
        /// <remarks/>
        public float score;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoreSpecified;
        
        /// <remarks/>
        public ResultSetRowNode node;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ResultSetRowNode
    {
        
        /// <remarks/>
        public string id;
        
        /// <remarks/>
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aspects")]
        public string[] aspects;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ResultSetMetaData
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valueDefs")]
        public ValueDefinition[] valueDefs;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classDefs")]
        public ClassDefinition[] classDefs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ContentFormat
    {
        
        /// <remarks/>
        public string mimetype;
        
        /// <remarks/>
        public string encoding;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Predicate
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nodes", typeof(Reference), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("query", typeof(Query), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("store", typeof(Store), IsNullable=true)]
        public object[] Items;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Query
    {
        
        /// <remarks/>
        public string language;
        
        /// <remarks/>
        public string statement;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CML
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("create")]
        public CMLCreate[] create;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addAspect")]
        public CMLAddAspect[] addAspect;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("removeAspect")]
        public CMLRemoveAspect[] removeAspect;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("update")]
        public CMLUpdate[] update;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("writeContent")]
        public CMLWriteContent[] writeContent;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delete")]
        public CMLDelete[] delete;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("move")]
        public CMLMove[] move;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("copy")]
        public CMLCopy[] copy;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addChild")]
        public CMLAddChild[] addChild;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("removeChild")]
        public CMLRemoveChild[] removeChild;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("createAssociation")]
        public CMLCreateAssociation[] createAssociation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("removeAssociation")]
        public CMLRemoveAssociation[] removeAssociation;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLCreate
    {
        
        /// <remarks/>
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ParentReference parent;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parent_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0", IsNullable=true)]
        public string associationType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0", IsNullable=true)]
        public string childName;
        
        /// <remarks/>
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public NamedValue[] property;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLAddAspect
    {
        
        /// <remarks/>
        public string aspect;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public NamedValue[] property;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate @where;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string where_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLRemoveAspect
    {
        
        /// <remarks/>
        public string aspect;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate @where;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string where_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLUpdate
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public NamedValue[] property;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate @where;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string where_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLWriteContent
    {
        
        /// <remarks/>
        public string property;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] content;
        
        /// <remarks/>
        public ContentFormat format;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate @where;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string where_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLDelete
    {
        
        /// <remarks/>
        public Predicate @where;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLMove
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ParentReference to;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string to_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0", IsNullable=true)]
        public string associationType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0", IsNullable=true)]
        public string childName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate @where;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string where_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLCopy
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ParentReference to;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string to_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0", IsNullable=true)]
        public string associationType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0", IsNullable=true)]
        public string childName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate @where;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string where_id;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool children;
        
        public CMLCopy()
        {
            this.children = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLAddChild
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ParentReference to;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string to_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0", IsNullable=true)]
        public string associationType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0", IsNullable=true)]
        public string childName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate @where;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string where_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLRemoveChild
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("from", typeof(Reference), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("from_id", typeof(string), IsNullable=true)]
        public object Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate @where;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string where_id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLCreateAssociation
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate from;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string from_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate to;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string to_id;
        
        /// <remarks/>
        public string association;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.alfresco.org/ws/cml/1.0")]
    public partial class CMLRemoveAssociation
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate from;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string from_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Predicate to;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string to_id;
        
        /// <remarks/>
        public string association;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/repository/1.0")]
    public partial class Association
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string associationType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string direction;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.0.5698")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/repository/1.0")]
    public partial class QueryResult
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string querySession;
        
        /// <remarks/>
        public ResultSet resultSet;
    }
}
