//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace Alfresco.AccessControlWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AccessControlServiceSoapBinding", Namespace="http://www.alfresco.org/ws/service/accesscontrol/1.0")]
    public partial class AccessControlService : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback getACLsOperationCompleted;
        
        private System.Threading.SendOrPostCallback addACEsOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeACEsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getClassPermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback hasPermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback setInheritPermissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOwnersOperationCompleted;
        
        private System.Threading.SendOrPostCallback setOwnersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AccessControlService() {
            this.Url = global::Alfresco.Properties.Settings.Default.Alfresco_AccessControlWebService_AccessControlService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getACLsCompletedEventHandler getACLsCompleted;
        
        /// <remarks/>
        public event addACEsCompletedEventHandler addACEsCompleted;
        
        /// <remarks/>
        public event removeACEsCompletedEventHandler removeACEsCompleted;
        
        /// <remarks/>
        public event getPermissionsCompletedEventHandler getPermissionsCompleted;
        
        /// <remarks/>
        public event getClassPermissionsCompletedEventHandler getClassPermissionsCompleted;
        
        /// <remarks/>
        public event hasPermissionsCompletedEventHandler hasPermissionsCompleted;
        
        /// <remarks/>
        public event setInheritPermissionCompletedEventHandler setInheritPermissionCompleted;
        
        /// <remarks/>
        public event getOwnersCompletedEventHandler getOwnersCompleted;
        
        /// <remarks/>
        public event setOwnersCompletedEventHandler setOwnersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/accesscontrol/1.0/getACLs", RequestNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("acls")]
        public ACL[] getACLs(Predicate predicate, ACE filter) {
            object[] results = this.Invoke("getACLs", new object[] {
                        predicate,
                        filter});
            return ((ACL[])(results[0]));
        }
        
        /// <remarks/>
        public void getACLsAsync(Predicate predicate, ACE filter) {
            this.getACLsAsync(predicate, filter, null);
        }
        
        /// <remarks/>
        public void getACLsAsync(Predicate predicate, ACE filter, object userState) {
            if ((this.getACLsOperationCompleted == null)) {
                this.getACLsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetACLsOperationCompleted);
            }
            this.InvokeAsync("getACLs", new object[] {
                        predicate,
                        filter}, this.getACLsOperationCompleted, userState);
        }
        
        private void OngetACLsOperationCompleted(object arg) {
            if ((this.getACLsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getACLsCompleted(this, new getACLsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/accesscontrol/1.0/addACEs", RequestNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("acls")]
        public ACL[] addACEs(Predicate predicate, [System.Xml.Serialization.XmlElementAttribute("aces")] ACE[] aces) {
            object[] results = this.Invoke("addACEs", new object[] {
                        predicate,
                        aces});
            return ((ACL[])(results[0]));
        }
        
        /// <remarks/>
        public void addACEsAsync(Predicate predicate, ACE[] aces) {
            this.addACEsAsync(predicate, aces, null);
        }
        
        /// <remarks/>
        public void addACEsAsync(Predicate predicate, ACE[] aces, object userState) {
            if ((this.addACEsOperationCompleted == null)) {
                this.addACEsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddACEsOperationCompleted);
            }
            this.InvokeAsync("addACEs", new object[] {
                        predicate,
                        aces}, this.addACEsOperationCompleted, userState);
        }
        
        private void OnaddACEsOperationCompleted(object arg) {
            if ((this.addACEsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addACEsCompleted(this, new addACEsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/accesscontrol/1.0/removeACEs", RequestNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("acls")]
        public ACL[] removeACEs(Predicate predicate, [System.Xml.Serialization.XmlElementAttribute("aces")] ACE[] aces) {
            object[] results = this.Invoke("removeACEs", new object[] {
                        predicate,
                        aces});
            return ((ACL[])(results[0]));
        }
        
        /// <remarks/>
        public void removeACEsAsync(Predicate predicate, ACE[] aces) {
            this.removeACEsAsync(predicate, aces, null);
        }
        
        /// <remarks/>
        public void removeACEsAsync(Predicate predicate, ACE[] aces, object userState) {
            if ((this.removeACEsOperationCompleted == null)) {
                this.removeACEsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveACEsOperationCompleted);
            }
            this.InvokeAsync("removeACEs", new object[] {
                        predicate,
                        aces}, this.removeACEsOperationCompleted, userState);
        }
        
        private void OnremoveACEsOperationCompleted(object arg) {
            if ((this.removeACEsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeACEsCompleted(this, new removeACEsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/accesscontrol/1.0/getPermissions", RequestNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public GetPermissionsResult[] getPermissions(Predicate predicate) {
            object[] results = this.Invoke("getPermissions", new object[] {
                        predicate});
            return ((GetPermissionsResult[])(results[0]));
        }
        
        /// <remarks/>
        public void getPermissionsAsync(Predicate predicate) {
            this.getPermissionsAsync(predicate, null);
        }
        
        /// <remarks/>
        public void getPermissionsAsync(Predicate predicate, object userState) {
            if ((this.getPermissionsOperationCompleted == null)) {
                this.getPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPermissionsOperationCompleted);
            }
            this.InvokeAsync("getPermissions", new object[] {
                        predicate}, this.getPermissionsOperationCompleted, userState);
        }
        
        private void OngetPermissionsOperationCompleted(object arg) {
            if ((this.getPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPermissionsCompleted(this, new getPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/accesscontrol/1.0/getClassPermissions", RequestNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public GetClassPermissionsResult[] getClassPermissions([System.Xml.Serialization.XmlElementAttribute("classNames")] string[] classNames) {
            object[] results = this.Invoke("getClassPermissions", new object[] {
                        classNames});
            return ((GetClassPermissionsResult[])(results[0]));
        }
        
        /// <remarks/>
        public void getClassPermissionsAsync(string[] classNames) {
            this.getClassPermissionsAsync(classNames, null);
        }
        
        /// <remarks/>
        public void getClassPermissionsAsync(string[] classNames, object userState) {
            if ((this.getClassPermissionsOperationCompleted == null)) {
                this.getClassPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetClassPermissionsOperationCompleted);
            }
            this.InvokeAsync("getClassPermissions", new object[] {
                        classNames}, this.getClassPermissionsOperationCompleted, userState);
        }
        
        private void OngetClassPermissionsOperationCompleted(object arg) {
            if ((this.getClassPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getClassPermissionsCompleted(this, new getClassPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/accesscontrol/1.0/hasPermissions", RequestNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("results")]
        public HasPermissionsResult[] hasPermissions(Predicate predicate, [System.Xml.Serialization.XmlElementAttribute("permissions")] string[] permissions) {
            object[] results = this.Invoke("hasPermissions", new object[] {
                        predicate,
                        permissions});
            return ((HasPermissionsResult[])(results[0]));
        }
        
        /// <remarks/>
        public void hasPermissionsAsync(Predicate predicate, string[] permissions) {
            this.hasPermissionsAsync(predicate, permissions, null);
        }
        
        /// <remarks/>
        public void hasPermissionsAsync(Predicate predicate, string[] permissions, object userState) {
            if ((this.hasPermissionsOperationCompleted == null)) {
                this.hasPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhasPermissionsOperationCompleted);
            }
            this.InvokeAsync("hasPermissions", new object[] {
                        predicate,
                        permissions}, this.hasPermissionsOperationCompleted, userState);
        }
        
        private void OnhasPermissionsOperationCompleted(object arg) {
            if ((this.hasPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hasPermissionsCompleted(this, new hasPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/accesscontrol/1.0/setInheritPermission", RequestNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("acls")]
        public ACL[] setInheritPermission(Predicate predicate, bool inheritPermission) {
            object[] results = this.Invoke("setInheritPermission", new object[] {
                        predicate,
                        inheritPermission});
            return ((ACL[])(results[0]));
        }
        
        /// <remarks/>
        public void setInheritPermissionAsync(Predicate predicate, bool inheritPermission) {
            this.setInheritPermissionAsync(predicate, inheritPermission, null);
        }
        
        /// <remarks/>
        public void setInheritPermissionAsync(Predicate predicate, bool inheritPermission, object userState) {
            if ((this.setInheritPermissionOperationCompleted == null)) {
                this.setInheritPermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetInheritPermissionOperationCompleted);
            }
            this.InvokeAsync("setInheritPermission", new object[] {
                        predicate,
                        inheritPermission}, this.setInheritPermissionOperationCompleted, userState);
        }
        
        private void OnsetInheritPermissionOperationCompleted(object arg) {
            if ((this.setInheritPermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setInheritPermissionCompleted(this, new setInheritPermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/accesscontrol/1.0/getOwners", RequestNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("results")]
        public OwnerResult[] getOwners(Predicate predicate) {
            object[] results = this.Invoke("getOwners", new object[] {
                        predicate});
            return ((OwnerResult[])(results[0]));
        }
        
        /// <remarks/>
        public void getOwnersAsync(Predicate predicate) {
            this.getOwnersAsync(predicate, null);
        }
        
        /// <remarks/>
        public void getOwnersAsync(Predicate predicate, object userState) {
            if ((this.getOwnersOperationCompleted == null)) {
                this.getOwnersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOwnersOperationCompleted);
            }
            this.InvokeAsync("getOwners", new object[] {
                        predicate}, this.getOwnersOperationCompleted, userState);
        }
        
        private void OngetOwnersOperationCompleted(object arg) {
            if ((this.getOwnersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOwnersCompleted(this, new getOwnersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/accesscontrol/1.0/setOwners", RequestNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/accesscontrol/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("results")]
        public OwnerResult[] setOwners(Predicate predicate, string owner) {
            object[] results = this.Invoke("setOwners", new object[] {
                        predicate,
                        owner});
            return ((OwnerResult[])(results[0]));
        }
        
        /// <remarks/>
        public void setOwnersAsync(Predicate predicate, string owner) {
            this.setOwnersAsync(predicate, owner, null);
        }
        
        /// <remarks/>
        public void setOwnersAsync(Predicate predicate, string owner, object userState) {
            if ((this.setOwnersOperationCompleted == null)) {
                this.setOwnersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetOwnersOperationCompleted);
            }
            this.InvokeAsync("setOwners", new object[] {
                        predicate,
                        owner}, this.setOwnersOperationCompleted, userState);
        }
        
        private void OnsetOwnersOperationCompleted(object arg) {
            if ((this.setOwnersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setOwnersCompleted(this, new setOwnersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Predicate {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nodes", typeof(Reference), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("query", typeof(Query), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("store", typeof(Store), IsNullable=true)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParentReference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Reference {
        
        private Store storeField;
        
        private string uuidField;
        
        private string pathField;
        
        public Reference() {
            this.pathField = "/";
        }
        
        /// <remarks/>
        public Store store {
            get {
                return this.storeField;
            }
            set {
                this.storeField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("/")]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Store {
        
        private StoreEnum schemeField;
        
        private string addressField;
        
        /// <remarks/>
        public StoreEnum scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public enum StoreEnum {
        
        /// <remarks/>
        workspace,
        
        /// <remarks/>
        versionStore,
        
        /// <remarks/>
        user,
        
        /// <remarks/>
        search,
        
        /// <remarks/>
        http,
        
        /// <remarks/>
        system,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/accesscontrol/1.0")]
    public partial class OwnerResult {
        
        private Reference referenceField;
        
        private string ownerField;
        
        /// <remarks/>
        public Reference reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/accesscontrol/1.0")]
    public partial class HasPermissionsResult {
        
        private Reference referenceField;
        
        private string permissionField;
        
        private AccessStatus accessStatusField;
        
        /// <remarks/>
        public Reference reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
        
        /// <remarks/>
        public AccessStatus accessStatus {
            get {
                return this.accessStatusField;
            }
            set {
                this.accessStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/accesscontrol/1.0")]
    public enum AccessStatus {
        
        /// <remarks/>
        acepted,
        
        /// <remarks/>
        declined,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/accesscontrol/1.0")]
    public partial class GetClassPermissionsResult {
        
        private string classNameField;
        
        private string[] permissionsField;
        
        /// <remarks/>
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("permissions")]
        public string[] permissions {
            get {
                return this.permissionsField;
            }
            set {
                this.permissionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/accesscontrol/1.0")]
    public partial class GetPermissionsResult {
        
        private Reference referenceField;
        
        private string[] permissionsField;
        
        /// <remarks/>
        public Reference reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("permissions")]
        public string[] permissions {
            get {
                return this.permissionsField;
            }
            set {
                this.permissionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/accesscontrol/1.0")]
    public partial class ACL {
        
        private Reference referenceField;
        
        private bool inheritPermissionsField;
        
        private ACE[] acesField;
        
        /// <remarks/>
        public Reference reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public bool inheritPermissions {
            get {
                return this.inheritPermissionsField;
            }
            set {
                this.inheritPermissionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aces")]
        public ACE[] aces {
            get {
                return this.acesField;
            }
            set {
                this.acesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/accesscontrol/1.0")]
    public partial class ACE {
        
        private string authorityField;
        
        private string permissionField;
        
        private AccessStatus accessStatusField;
        
        /// <remarks/>
        public string authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
        
        /// <remarks/>
        public AccessStatus accessStatus {
            get {
                return this.accessStatusField;
            }
            set {
                this.accessStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Query {
        
        private QueryLanguageEnum languageField;
        
        private string statementField;
        
        /// <remarks/>
        public QueryLanguageEnum language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string statement {
            get {
                return this.statementField;
            }
            set {
                this.statementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public enum QueryLanguageEnum {
        
        /// <remarks/>
        lucene,
        
        /// <remarks/>
        xpath,
        
        /// <remarks/>
        cql,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ParentReference : Reference {
        
        private string associationTypeField;
        
        private string childNameField;
        
        /// <remarks/>
        public string associationType {
            get {
                return this.associationTypeField;
            }
            set {
                this.associationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string childName {
            get {
                return this.childNameField;
            }
            set {
                this.childNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getACLsCompletedEventHandler(object sender, getACLsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getACLsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getACLsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACL[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACL[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void addACEsCompletedEventHandler(object sender, addACEsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addACEsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addACEsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACL[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACL[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void removeACEsCompletedEventHandler(object sender, removeACEsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeACEsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeACEsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACL[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACL[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getPermissionsCompletedEventHandler(object sender, getPermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetPermissionsResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetPermissionsResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getClassPermissionsCompletedEventHandler(object sender, getClassPermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getClassPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getClassPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetClassPermissionsResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetClassPermissionsResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void hasPermissionsCompletedEventHandler(object sender, hasPermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hasPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hasPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HasPermissionsResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HasPermissionsResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void setInheritPermissionCompletedEventHandler(object sender, setInheritPermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setInheritPermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setInheritPermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACL[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACL[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getOwnersCompletedEventHandler(object sender, getOwnersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOwnersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOwnersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OwnerResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OwnerResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void setOwnersCompletedEventHandler(object sender, setOwnersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setOwnersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setOwnersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OwnerResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OwnerResult[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591