//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace Alfresco.AuthoringWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthoringServiceSoapBinding", Namespace="http://www.alfresco.org/ws/service/authoring/1.0")]
    public partial class AuthoringService : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback checkoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkinOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkinExternalOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelCheckoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback lockOperationCompleted;
        
        private System.Threading.SendOrPostCallback unlockOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLockStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback createVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVersionHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback revertVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteAllVersionsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AuthoringService() {
            this.Url = global::Alfresco.Properties.Settings.Default.Alfresco_AuthoringWebService_AuthoringService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event checkoutCompletedEventHandler checkoutCompleted;
        
        /// <remarks/>
        public event checkinCompletedEventHandler checkinCompleted;
        
        /// <remarks/>
        public event checkinExternalCompletedEventHandler checkinExternalCompleted;
        
        /// <remarks/>
        public event cancelCheckoutCompletedEventHandler cancelCheckoutCompleted;
        
        /// <remarks/>
        public event lockCompletedEventHandler lockCompleted;
        
        /// <remarks/>
        public event unlockCompletedEventHandler unlockCompleted;
        
        /// <remarks/>
        public event getLockStatusCompletedEventHandler getLockStatusCompleted;
        
        /// <remarks/>
        public event createVersionCompletedEventHandler createVersionCompleted;
        
        /// <remarks/>
        public event getVersionHistoryCompletedEventHandler getVersionHistoryCompleted;
        
        /// <remarks/>
        public event revertVersionCompletedEventHandler revertVersionCompleted;
        
        /// <remarks/>
        public event deleteAllVersionsCompletedEventHandler deleteAllVersionsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/authoring/1.0/checkout", RequestNamespace="http://www.alfresco.org/ws/service/authoring/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/authoring/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("checkoutReturn")]
        public CheckoutResult checkout(Predicate items, ParentReference destination) {
            object[] results = this.Invoke("checkout", new object[] {
                        items,
                        destination});
            return ((CheckoutResult)(results[0]));
        }
        
        /// <remarks/>
        public void checkoutAsync(Predicate items, ParentReference destination) {
            this.checkoutAsync(items, destination, null);
        }
        
        /// <remarks/>
        public void checkoutAsync(Predicate items, ParentReference destination, object userState) {
            if ((this.checkoutOperationCompleted == null)) {
                this.checkoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckoutOperationCompleted);
            }
            this.InvokeAsync("checkout", new object[] {
                        items,
                        destination}, this.checkoutOperationCompleted, userState);
        }
        
        private void OncheckoutOperationCompleted(object arg) {
            if ((this.checkoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkoutCompleted(this, new checkoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/authoring/1.0/checkin", RequestNamespace="http://www.alfresco.org/ws/service/authoring/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/authoring/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("checkinReturn")]
        public CheckinResult checkin(Predicate items, [System.Xml.Serialization.XmlElementAttribute("comments")] NamedValue[] comments, bool keepCheckedOut) {
            object[] results = this.Invoke("checkin", new object[] {
                        items,
                        comments,
                        keepCheckedOut});
            return ((CheckinResult)(results[0]));
        }
        
        /// <remarks/>
        public void checkinAsync(Predicate items, NamedValue[] comments, bool keepCheckedOut) {
            this.checkinAsync(items, comments, keepCheckedOut, null);
        }
        
        /// <remarks/>
        public void checkinAsync(Predicate items, NamedValue[] comments, bool keepCheckedOut, object userState) {
            if ((this.checkinOperationCompleted == null)) {
                this.checkinOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckinOperationCompleted);
            }
            this.InvokeAsync("checkin", new object[] {
                        items,
                        comments,
                        keepCheckedOut}, this.checkinOperationCompleted, userState);
        }
        
        private void OncheckinOperationCompleted(object arg) {
            if ((this.checkinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkinCompleted(this, new checkinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/authoring/1.0/checkinExternal", RequestNamespace="http://www.alfresco.org/ws/service/authoring/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/authoring/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("checkinExternalReturn")]
        public Reference checkinExternal(Reference items, [System.Xml.Serialization.XmlElementAttribute("comments")] NamedValue[] comments, bool keepCheckedOut, ContentFormat format, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] content) {
            object[] results = this.Invoke("checkinExternal", new object[] {
                        items,
                        comments,
                        keepCheckedOut,
                        format,
                        content});
            return ((Reference)(results[0]));
        }
        
        /// <remarks/>
        public void checkinExternalAsync(Reference items, NamedValue[] comments, bool keepCheckedOut, ContentFormat format, byte[] content) {
            this.checkinExternalAsync(items, comments, keepCheckedOut, format, content, null);
        }
        
        /// <remarks/>
        public void checkinExternalAsync(Reference items, NamedValue[] comments, bool keepCheckedOut, ContentFormat format, byte[] content, object userState) {
            if ((this.checkinExternalOperationCompleted == null)) {
                this.checkinExternalOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckinExternalOperationCompleted);
            }
            this.InvokeAsync("checkinExternal", new object[] {
                        items,
                        comments,
                        keepCheckedOut,
                        format,
                        content}, this.checkinExternalOperationCompleted, userState);
        }
        
        private void OncheckinExternalOperationCompleted(object arg) {
            if ((this.checkinExternalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkinExternalCompleted(this, new checkinExternalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/authoring/1.0/cancelCheckout", RequestNamespace="http://www.alfresco.org/ws/service/authoring/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/authoring/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("cancelCheckoutReturn")]
        public CancelCheckoutResult cancelCheckout(Predicate items) {
            object[] results = this.Invoke("cancelCheckout", new object[] {
                        items});
            return ((CancelCheckoutResult)(results[0]));
        }
        
        /// <remarks/>
        public void cancelCheckoutAsync(Predicate items) {
            this.cancelCheckoutAsync(items, null);
        }
        
        /// <remarks/>
        public void cancelCheckoutAsync(Predicate items, object userState) {
            if ((this.cancelCheckoutOperationCompleted == null)) {
                this.cancelCheckoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelCheckoutOperationCompleted);
            }
            this.InvokeAsync("cancelCheckout", new object[] {
                        items}, this.cancelCheckoutOperationCompleted, userState);
        }
        
        private void OncancelCheckoutOperationCompleted(object arg) {
            if ((this.cancelCheckoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelCheckoutCompleted(this, new cancelCheckoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/authoring/1.0/lock", RequestNamespace="http://www.alfresco.org/ws/service/authoring/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/authoring/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("lockReturn")]
        public Reference[] @lock(Predicate items, bool lockChildren, LockTypeEnum lockType) {
            object[] results = this.Invoke("lock", new object[] {
                        items,
                        lockChildren,
                        lockType});
            return ((Reference[])(results[0]));
        }
        
        /// <remarks/>
        public void lockAsync(Predicate items, bool lockChildren, LockTypeEnum lockType) {
            this.lockAsync(items, lockChildren, lockType, null);
        }
        
        /// <remarks/>
        public void lockAsync(Predicate items, bool lockChildren, LockTypeEnum lockType, object userState) {
            if ((this.lockOperationCompleted == null)) {
                this.lockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlockOperationCompleted);
            }
            this.InvokeAsync("lock", new object[] {
                        items,
                        lockChildren,
                        lockType}, this.lockOperationCompleted, userState);
        }
        
        private void OnlockOperationCompleted(object arg) {
            if ((this.lockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lockCompleted(this, new lockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/authoring/1.0/unlock", RequestNamespace="http://www.alfresco.org/ws/service/authoring/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/authoring/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("unlockReturn")]
        public Reference[] unlock(Predicate items, bool unlockChildren) {
            object[] results = this.Invoke("unlock", new object[] {
                        items,
                        unlockChildren});
            return ((Reference[])(results[0]));
        }
        
        /// <remarks/>
        public void unlockAsync(Predicate items, bool unlockChildren) {
            this.unlockAsync(items, unlockChildren, null);
        }
        
        /// <remarks/>
        public void unlockAsync(Predicate items, bool unlockChildren, object userState) {
            if ((this.unlockOperationCompleted == null)) {
                this.unlockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunlockOperationCompleted);
            }
            this.InvokeAsync("unlock", new object[] {
                        items,
                        unlockChildren}, this.unlockOperationCompleted, userState);
        }
        
        private void OnunlockOperationCompleted(object arg) {
            if ((this.unlockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unlockCompleted(this, new unlockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/authoring/1.0/getLockStatus", RequestNamespace="http://www.alfresco.org/ws/service/authoring/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/authoring/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getLockStatusReturn")]
        public LockStatus[] getLockStatus(Predicate items) {
            object[] results = this.Invoke("getLockStatus", new object[] {
                        items});
            return ((LockStatus[])(results[0]));
        }
        
        /// <remarks/>
        public void getLockStatusAsync(Predicate items) {
            this.getLockStatusAsync(items, null);
        }
        
        /// <remarks/>
        public void getLockStatusAsync(Predicate items, object userState) {
            if ((this.getLockStatusOperationCompleted == null)) {
                this.getLockStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLockStatusOperationCompleted);
            }
            this.InvokeAsync("getLockStatus", new object[] {
                        items}, this.getLockStatusOperationCompleted, userState);
        }
        
        private void OngetLockStatusOperationCompleted(object arg) {
            if ((this.getLockStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLockStatusCompleted(this, new getLockStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/authoring/1.0/createVersion", RequestNamespace="http://www.alfresco.org/ws/service/authoring/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/authoring/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("createVersionReturn")]
        public VersionResult createVersion(Predicate items, [System.Xml.Serialization.XmlElementAttribute("comments")] NamedValue[] comments, bool versionChildren) {
            object[] results = this.Invoke("createVersion", new object[] {
                        items,
                        comments,
                        versionChildren});
            return ((VersionResult)(results[0]));
        }
        
        /// <remarks/>
        public void createVersionAsync(Predicate items, NamedValue[] comments, bool versionChildren) {
            this.createVersionAsync(items, comments, versionChildren, null);
        }
        
        /// <remarks/>
        public void createVersionAsync(Predicate items, NamedValue[] comments, bool versionChildren, object userState) {
            if ((this.createVersionOperationCompleted == null)) {
                this.createVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateVersionOperationCompleted);
            }
            this.InvokeAsync("createVersion", new object[] {
                        items,
                        comments,
                        versionChildren}, this.createVersionOperationCompleted, userState);
        }
        
        private void OncreateVersionOperationCompleted(object arg) {
            if ((this.createVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createVersionCompleted(this, new createVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/authoring/1.0/getVersionHistory", RequestNamespace="http://www.alfresco.org/ws/service/authoring/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/authoring/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getVersionHistoryReturn")]
        public VersionHistory getVersionHistory(Reference node) {
            object[] results = this.Invoke("getVersionHistory", new object[] {
                        node});
            return ((VersionHistory)(results[0]));
        }
        
        /// <remarks/>
        public void getVersionHistoryAsync(Reference node) {
            this.getVersionHistoryAsync(node, null);
        }
        
        /// <remarks/>
        public void getVersionHistoryAsync(Reference node, object userState) {
            if ((this.getVersionHistoryOperationCompleted == null)) {
                this.getVersionHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVersionHistoryOperationCompleted);
            }
            this.InvokeAsync("getVersionHistory", new object[] {
                        node}, this.getVersionHistoryOperationCompleted, userState);
        }
        
        private void OngetVersionHistoryOperationCompleted(object arg) {
            if ((this.getVersionHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVersionHistoryCompleted(this, new getVersionHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/authoring/1.0/revertVersion", RequestNamespace="http://www.alfresco.org/ws/service/authoring/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/authoring/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void revertVersion(Reference node, string versionLabel) {
            this.Invoke("revertVersion", new object[] {
                        node,
                        versionLabel});
        }
        
        /// <remarks/>
        public void revertVersionAsync(Reference node, string versionLabel) {
            this.revertVersionAsync(node, versionLabel, null);
        }
        
        /// <remarks/>
        public void revertVersionAsync(Reference node, string versionLabel, object userState) {
            if ((this.revertVersionOperationCompleted == null)) {
                this.revertVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrevertVersionOperationCompleted);
            }
            this.InvokeAsync("revertVersion", new object[] {
                        node,
                        versionLabel}, this.revertVersionOperationCompleted, userState);
        }
        
        private void OnrevertVersionOperationCompleted(object arg) {
            if ((this.revertVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.revertVersionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alfresco.org/ws/service/authoring/1.0/deleteAllVersions", RequestNamespace="http://www.alfresco.org/ws/service/authoring/1.0", ResponseNamespace="http://www.alfresco.org/ws/service/authoring/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("deleteAllVersionsReturn")]
        public VersionHistory deleteAllVersions(Reference node) {
            object[] results = this.Invoke("deleteAllVersions", new object[] {
                        node});
            return ((VersionHistory)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAllVersionsAsync(Reference node) {
            this.deleteAllVersionsAsync(node, null);
        }
        
        /// <remarks/>
        public void deleteAllVersionsAsync(Reference node, object userState) {
            if ((this.deleteAllVersionsOperationCompleted == null)) {
                this.deleteAllVersionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteAllVersionsOperationCompleted);
            }
            this.InvokeAsync("deleteAllVersions", new object[] {
                        node}, this.deleteAllVersionsOperationCompleted, userState);
        }
        
        private void OndeleteAllVersionsOperationCompleted(object arg) {
            if ((this.deleteAllVersionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteAllVersionsCompleted(this, new deleteAllVersionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Predicate {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nodes", typeof(Reference), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("query", typeof(Query), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("store", typeof(Store), IsNullable=true)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParentReference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Reference {
        
        private Store storeField;
        
        private string uuidField;
        
        private string pathField;
        
        public Reference() {
            this.pathField = "/";
        }
        
        /// <remarks/>
        public Store store {
            get {
                return this.storeField;
            }
            set {
                this.storeField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("/")]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Store {
        
        private StoreEnum schemeField;
        
        private string addressField;
        
        /// <remarks/>
        public StoreEnum scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public enum StoreEnum {
        
        /// <remarks/>
        workspace,
        
        /// <remarks/>
        versionStore,
        
        /// <remarks/>
        user,
        
        /// <remarks/>
        search,
        
        /// <remarks/>
        http,
        
        /// <remarks/>
        system,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class VersionHistory {
        
        private string markerField;
        
        private Version[] versionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string marker {
            get {
                return this.markerField;
            }
            set {
                this.markerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("versions")]
        public Version[] versions {
            get {
                return this.versionsField;
            }
            set {
                this.versionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Version {
        
        private Reference idField;
        
        private System.DateTime createdField;
        
        private bool createdFieldSpecified;
        
        private string creatorField;
        
        private string labelField;
        
        private bool majorField;
        
        private NamedValue[] commentariesField;
        
        public Version() {
            this.majorField = true;
        }
        
        /// <remarks/>
        public Reference id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public bool major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("commentaries")]
        public NamedValue[] commentaries {
            get {
                return this.commentariesField;
            }
            set {
                this.commentariesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class NamedValue {
        
        private string nameField;
        
        private System.Nullable<bool> isMultiValueField;
        
        private string valueField;
        
        private string[] valuesField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isMultiValue {
            get {
                return this.isMultiValueField;
            }
            set {
                this.isMultiValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("values", IsNullable=true)]
        public string[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/authoring/1.0")]
    public partial class VersionResult {
        
        private Reference[] nodesField;
        
        private Version[] versionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nodes")]
        public Reference[] nodes {
            get {
                return this.nodesField;
            }
            set {
                this.nodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("versions")]
        public Version[] versions {
            get {
                return this.versionsField;
            }
            set {
                this.versionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/authoring/1.0")]
    public partial class LockStatus {
        
        private Reference nodeField;
        
        private System.Nullable<LockTypeEnum> lockTypeField;
        
        private bool lockTypeFieldSpecified;
        
        private string lockOwnerField;
        
        /// <remarks/>
        public Reference node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<LockTypeEnum> lockType {
            get {
                return this.lockTypeField;
            }
            set {
                this.lockTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lockTypeSpecified {
            get {
                return this.lockTypeFieldSpecified;
            }
            set {
                this.lockTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lockOwner {
            get {
                return this.lockOwnerField;
            }
            set {
                this.lockOwnerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/authoring/1.0")]
    public enum LockTypeEnum {
        
        /// <remarks/>
        read,
        
        /// <remarks/>
        write,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/authoring/1.0")]
    public partial class CancelCheckoutResult {
        
        private Reference[] workingCopiesField;
        
        private Reference[] originalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("workingCopies")]
        public Reference[] workingCopies {
            get {
                return this.workingCopiesField;
            }
            set {
                this.workingCopiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("originals")]
        public Reference[] originals {
            get {
                return this.originalsField;
            }
            set {
                this.originalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ContentFormat {
        
        private string mimetypeField;
        
        private string encodingField;
        
        /// <remarks/>
        public string mimetype {
            get {
                return this.mimetypeField;
            }
            set {
                this.mimetypeField = value;
            }
        }
        
        /// <remarks/>
        public string encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/authoring/1.0")]
    public partial class CheckinResult {
        
        private Reference[] workingCopiesField;
        
        private Reference[] checkedInField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("workingCopies")]
        public Reference[] workingCopies {
            get {
                return this.workingCopiesField;
            }
            set {
                this.workingCopiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("checkedIn")]
        public Reference[] checkedIn {
            get {
                return this.checkedInField;
            }
            set {
                this.checkedInField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/service/authoring/1.0")]
    public partial class CheckoutResult {
        
        private Reference[] originalsField;
        
        private Reference[] workingCopiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("originals")]
        public Reference[] originals {
            get {
                return this.originalsField;
            }
            set {
                this.originalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("workingCopies")]
        public Reference[] workingCopies {
            get {
                return this.workingCopiesField;
            }
            set {
                this.workingCopiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class Query {
        
        private QueryLanguageEnum languageField;
        
        private string statementField;
        
        /// <remarks/>
        public QueryLanguageEnum language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string statement {
            get {
                return this.statementField;
            }
            set {
                this.statementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public enum QueryLanguageEnum {
        
        /// <remarks/>
        lucene,
        
        /// <remarks/>
        xpath,
        
        /// <remarks/>
        cql,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alfresco.org/ws/model/content/1.0")]
    public partial class ParentReference : Reference {
        
        private string associationTypeField;
        
        private string childNameField;
        
        /// <remarks/>
        public string associationType {
            get {
                return this.associationTypeField;
            }
            set {
                this.associationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string childName {
            get {
                return this.childNameField;
            }
            set {
                this.childNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void checkoutCompletedEventHandler(object sender, checkoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CheckoutResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CheckoutResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void checkinCompletedEventHandler(object sender, checkinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CheckinResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CheckinResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void checkinExternalCompletedEventHandler(object sender, checkinExternalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkinExternalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkinExternalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reference Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reference)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void cancelCheckoutCompletedEventHandler(object sender, cancelCheckoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelCheckoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelCheckoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelCheckoutResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelCheckoutResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void lockCompletedEventHandler(object sender, lockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reference[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reference[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void unlockCompletedEventHandler(object sender, unlockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class unlockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal unlockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reference[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reference[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getLockStatusCompletedEventHandler(object sender, getLockStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLockStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLockStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LockStatus[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LockStatus[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void createVersionCompletedEventHandler(object sender, createVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VersionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VersionResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getVersionHistoryCompletedEventHandler(object sender, getVersionHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVersionHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVersionHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VersionHistory Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VersionHistory)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void revertVersionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void deleteAllVersionsCompletedEventHandler(object sender, deleteAllVersionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteAllVersionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteAllVersionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VersionHistory Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VersionHistory)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591